dataset: imagenet1000

model: podnet
convnet: rebuffi

convnet: resnet18
convnet_config:
  nf: 64

batch_size: 64
memory_size: 20000

eval_type: cnn

classifier_config:
  type: cosine
  proxy_per_class: 10
  distance: neg_stable_cosine_distance

postprocessor_config:
  type: learned_scaling
  initial_value: 1.0

pod_flat:
  scheduled_factor: 10.0

pod_spatial:
  scheduled_factor: 8.0
  collapse_channels: spatial

nca:
  margin: 0.6
  scale: 1.
  exclude_pos_denominator: true

groupwise_factors:
  old_weights: 0.

finetuning_config:
  sampling: undersampling
  tuning: classifier
  lr: 0.01
  epochs: 20
  scaling: null

# Cosine Scheduling (CS)
scheduling: cosine

# Misc
epochs: 90
lr: 0.05
lr_decay: 0.1
optimizer: sgd
proxy_per_class: 1
weight_decay: 0.0001

weight_generation:
  type: imprinted
  multi_class_diff: kmeans

dataset_transforms:
  color_jitter: true
