dataset: imagenet100
validation: 0.1

model: bic
convnet: resnet18
convnet_config:
  nf: 64

batch_size: 64

classifier_config:
  type: fc

temperature: 2.

lr: 0.025
weight_decay: 0.0001
scheduling:
  - 30
  - 60
  - 80
  - 90
lr_decay: 0.1
optimizer: sgd
epochs: 100
