# I haven't been able to reproduce LwM results!
# And since official code is not available, I'm not sure how to solve that.

model: lwm
convnet: resnet34

memory_size: 2000

distillation_config:
  factor: 1.0

attention_config:
  factor: 0.1

lr: 0.01
weight_decay: 0.00005
scheduling: null
lr_decay: 0.2
optimizer: sgd_nesterov
epochs: 1

dataset_transforms:
  color_jitter: false
